### ISSUE TITLE
Burrito sefgaults on Fedora release 37

### ISSUE THREAD

**Issue by kpanic** [burrito-elixir/burrito#81] opened 2023-03-09 18:52 UTC
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: `Manjaro testing`
**Host CPU**: `x86_64`

Please run `zig version` in your Burrito project directory and write the version here: 
`0.10.0`

Please run `elixir -v` in your Burrito project directory and write the version here:
```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 25)
```
------

### Target

**Host OS**:  `Fedora release 37`
**Host CPU**: `x86_64`
**Host LibC and Version**: `glibc-2.36`

------

Hello folks,

I copied my burrito binary on a Fedora machine from a Manjaro testing (AKA arch) and got:

```bash
$ ./gigex_cli_linux 
/home/kpanic/.local/share/.burrito/gigex_cli_erts-13.1.2_0.1.1/erts-13.1.2/bin/beam.smp: /lib64/libncursesw.so.6: 
no version information available (required by 
/home/kpanic/.local/share/.burrito/gigex_cli_erts-13.1.2_0.1.1/erts-13.1.2/bin/beam.smp)
Failed to create scheduler thread 79, error = 11
Aborted (core dumped)
```

Have you already seen something like this?

**Thanks a lot for the fantastic project!**

**Comment by doawoo** [comment] 2023-03-09 19:07
Thanks for the report! I suspect there's a version mismatch between the libncurses Manjaro has, and the one fedora ships with. Since both host and target are x86_64, Burrito is copying the local ERTS from your Manjaro system into the archive.

Fedora is probably running an older version of libncurses vs Arch/Manjaro, so I suspect that's what's going on. 

I'll try and reproduce this to confirm, but you could try to download a static ERTS from our Erlang Builder (https://github.com/burrito-elixir/erlang-builder/releases/tag/OTP-25.2.3) and specify that releases use that specific tar.gz file as the custom ERTS source in your `mix.exs` (https://github.com/burrito-elixir/burrito#using-custom-erts-builds)

And see if that makes Fedora happy

**Comment by kpanic** [comment] 2023-03-09 19:17
Hey @doawoo, thanks for the super quick response!

I tried to put in my `mix.exs` file:

```elixir
gigex_cli: [
        steps: [:assemble, &Burrito.wrap/1],
        burrito: [
          targets: [
            macos: [os: :darwin, cpu: :x86_64],
            linux: [os: :linux, cpu: :x86_64, custom_erts: "otp-25.2.3-linux-x86_64.tar.gz"],
            windows: [os: :windows, cpu: :x86_64]
          ]
        ]
      ]
```

and downloaded otp-25.2.3-linux-x86_64.tar.gz from https://github.com/burrito-elixir/erlang-builder/releases/tag/OTP-25.2.3

and:

```elixir
BURRITO_TARGET=linux MIX_ENV=prod mix release                    ✔  32s  
Generated gigex app
Release gigex_cli-0.1.1 already exists. Overwrite? [Yn] 
* assembling gigex_cli-0.1.1 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
-> Target is being overridden with BURRITO_TARGET linux
-> Burrito is building target: linux
-> Burrito will build for target:
	OS: linux
	CPU: x86_64
	Qualifiers: [libc: :glibc]
	Debug: false
--> PHASE: :fetch
---> Working directory: /tmp/burrito_build_579DD09EE6F45453
---> Resolving ERTS: {:local, [path: "otp-25.2.3-linux-x86_64.tar.gz"]}
---> Unpacked ERTS to: /tmp/unpacked_erts_B472ACD3E731C985
--> PHASE: :patch
---> Replacing ERTS binaries...
---> Overwriting NIF library /tmp/burrito_build_579DD09EE6F45453/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so with /tmp/unpacked_erts_B472ACD3E731C985/otp-25.2.3-linux-x86_64/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so
---> Overwriting NIF library /tmp/burrito_build_579DD09EE6F45453/lib/crypto-5.1.2/priv/lib/crypto.so with /tmp/unpacked_erts_B472ACD3E731C985/otp-25.2.3-linux-x86_64/lib/crypto-5.1.2/priv/lib/crypto.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/crypto-5.1.2/priv/lib/crypto.so
---> Overwriting NIF library /tmp/burrito_build_579DD09EE6F45453/lib/crypto-5.1.2/priv/lib/otp_test_engine.so with /tmp/unpacked_erts_B472ACD3E731C985/otp-25.2.3-linux-x86_64/lib/crypto-5.1.2/priv/lib/otp_test_engine.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/crypto-5.1.2/priv/lib/otp_test_engine.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/megaco-4.4.2/priv/lib/megaco_flex_scanner_drv.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/megaco-4.4.2/priv/lib/megaco_flex_scanner_drv_mt.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/runtime_tools-1.19/priv/lib/dyntrace.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/runtime_tools-1.19/priv/lib/trace_file_drv.so
---> Installed NIF library /tmp/burrito_build_579DD09EE6F45453/lib/runtime_tools-1.19/priv/lib/trace_ip_drv.so
--> PHASE: :build
---> Generating wrapper metadata file...
info: Zig is building an Elixir binary... ⚡
info: Generating and compressing release payload... 📦
info: 🔍 Files Packed: 994
info: Archived 994 files into payload! 📥
info: Building wrapper and embedding payload... 🌯
info: DONE 🚀
---> Cleaning up...
```

However, I got the same error

```
/home/kpanic/.local/share/.burrito/gigex_cli_erts-13.1.2_0.1.1/erts-13.1.2/bin/beam.smp: /lib64/libncursesw.so.6: 
no version information available (required by 
/home/kpanic/.local/share/.burrito/gigex_cli_erts-13.1.2_0.1.1/erts-13.1.2/bin/beam.smp)
Failed to create scheduler thread 79, error = 11
Aborted (core dumped)
```

**Comment by doawoo** [comment] 2023-03-14 01:57
Alright I took some time to try out a few thing... Turns out the `erlang-builder` ERTSs aren't as stable on other systems.

The GOOD NEWS is the newer "BEAM Machine" builds do work on Fedora 37 are are actually static! There's a branch of burrito I'm still testing out called `digit/beam-machine-download` that replaced the GitHub backed ERTS CDN with the new custom one I've built.

Try downloading an ERTS release from here: https://beammachine.cloud and do the same `custom_erts` replacement. See if that solves your issue. I was able to build the example CLI app with that release.

**Comment by kpanic** [comment] 2023-03-14 07:38
Hi @doawoo 👋🏾 Thanks for following up.

I changed my `mix.exs` with:

```elixir
{:burrito, github: "burrito-elixir/burrito", branch: "digit/beam-machine-download"},
```

pointed to:

```
 def releases do
    [
      gigex_cli: [
        steps: [:assemble, &Burrito.wrap/1],
        burrito: [
          targets: [
            macos: [os: :darwin, cpu: :x86_64],
            linux: [os: :linux, cpu: :x86_64, custom_erts: "otp_25.2.3_linux_gnu_x86_64_ssl_1.1.1s.tar.gz"],
            windows: [os: :windows, cpu: :x86_64]
          ]
        ]
      ]
    ]
  end
```

Downloaded from https://beammachine.cloud

and re-run:

```bash
$ BURRITO_TARGET=linux MIX_ENV=prod mix release
Release gigex_cli-0.1.1 already exists. Overwrite? [Yn] 
* assembling gigex_cli-0.1.1 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
> Target is being overridden with BURRITO_TARGET linux
> Burrito is building target: linux
> Burrito will build for target:
	OS: linux
	CPU: x86_64
	Qualifiers: [libc: :gnu]
	Debug: false
----> PHASE: :fetch
--> Working directory: /tmp/burrito_build_A458D050B340DD00
--> Resolving ERTS: {:local, [path: "otp_25.2.3_linux_gnu_x86_64_ssl_1.1.1s.tar.gz"]}
--> Unpacked ERTS to: /tmp/unpacked_erts_50DB90AE4E6EBCFD
----> PHASE: :patch
--> Replacing ERTS binaries...
--> Overwriting NIF library /tmp/burrito_build_A458D050B340DD00/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so with /tmp/unpacked_erts_50DB90AE4E6EBCFD/otp_25.2.3_linux_gnu_x86_64_ssl_1.1.1s/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so
--> Overwriting NIF library /tmp/burrito_build_A458D050B340DD00/lib/crypto-5.1.2/priv/lib/crypto.so with /tmp/unpacked_erts_50DB90AE4E6EBCFD/otp_25.2.3_linux_gnu_x86_64_ssl_1.1.1s/lib/crypto-5.1.2/priv/lib/crypto.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/crypto-5.1.2/priv/lib/crypto.so
--> Overwriting NIF library /tmp/burrito_build_A458D050B340DD00/lib/crypto-5.1.2/priv/lib/otp_test_engine.so with /tmp/unpacked_erts_50DB90AE4E6EBCFD/otp_25.2.3_linux_gnu_x86_64_ssl_1.1.1s/lib/crypto-5.1.2/priv/lib/otp_test_engine.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/crypto-5.1.2/priv/lib/otp_test_engine.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/megaco-4.4.2/priv/lib/megaco_flex_scanner_drv.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/megaco-4.4.2/priv/lib/megaco_flex_scanner_drv_mt.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/runtime_tools-1.19/priv/lib/dyntrace.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/runtime_tools-1.19/priv/lib/trace_file_drv.so
--> Installed NIF library /tmp/burrito_build_A458D050B340DD00/lib/runtime_tools-1.19/priv/lib/trace_ip_drv.so
----> PHASE: :build
--> Generating wrapper metadata file...
info: Zig is building an Elixir binary... ⚡
info: Generating and compressing release payload... 📦
info: 🔍 Files Packed: 994
info: Archived 994 files into payload! 📥
info: Building wrapper and embedding payload... 🌯
info: DONE 🚀
--> Cleaning up...



🌯 Burrito has wrapped your Elixir app! 🌯
	Output Path: /home/kpanic/src/gigex/burrito_out/gigex_cli_linux



Release created at _build/prod/rel/gigex_cli

    # To start your system
    _build/prod/rel/gigex_cli/bin/gigex_cli start

Once the release is running:

    # To connect to it remotely
    _build/prod/rel/gigex_cli/bin/gigex_cli remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/prod/rel/gigex_cli/bin/gigex_cli stop

To list all commands:

    _build/prod/rel/gigex_cli/bin/gigex_cli
```

Then I obtained on the Fedora:

```bash
$ GIGEX_MODE=CLI ./gigex_cli_linux 
/home/kpanic/.local/share/.burrito/gigex_cli_erts-13.1.2_0.1.1/erts-13.1.2/bin/beam.smp: /lib64/libncursesw.so.6: no version information available (required by /home/kpanic/.local/share/.burrito/gigex_cli_erts-13.1.2_0.1.1/erts-13.1.2/bin/beam.smp)
Failed to create scheduler thread 79, error = 11
Aborted (core dumped)
```

**Comment by doawoo** [comment] 2023-03-14 13:46
Aha, I just noticed something in your logs, you're using burrito in production mode.
If you use a burrito wrapped app, in prod mode, with the same version number on a machine that already has run once before, it will not re-extract the wrapped application since it assumes it hasn't changed...

Try blowing away the `/home/kpanic/.local/share/.burrito/` folder on your target machine, and re-run a build that's using the BEAM Machine ERTS. 

If you explicitly run burrito apps in non prod mode (which defaults when `MIX_ENV != :prod` then burrito wrapped apps will _always_ re-extract and skip the version test.

Perhaps I should look into a more robust way to detect difference between releases to ensure this isn't confusing 😅

**Comment by kpanic** [comment] 2023-03-14 14:35
Maybe the `mix release --force` option can help? Just guessing.
I will try later during this day to remove that folder. thanks @doawoo !

**Comment by doawoo** [comment] 2023-03-14 22:26
Hmm that's at least a _different_ error... I appreciate your continued trouble shooting here!

Here are my next 2 thoughts

1. Do you have any NIFs you are using?
2. Are you able to build the app inside the `example/` directory in the repo, and if so does that work on the Fedora machine.

**Comment by doawoo** [comment] 2023-03-14 22:30
Also would this happen to be the Repo `gigex` on your public GH page? If so I'll try out that code locally :)

**Comment by kpanic** [comment] 2023-03-15 05:48
You are welcome!

I tried the example app with the branch `digit/beam-machine-download` *without* the beam machine download and got:

```elixir
$ ./example_cli_app_linux_gnu 
/home/kpanic/.local/share/.burrito/example_cli_app_erts-13.1.2_0.1.0/erts-13.1.2/bin/beam.smp: /lib64/libncursesw.so.6: no version information available (required by /home/kpanic/.local/share/.burrito/example_cli_app_erts-13.1.2_0.1.0/erts-13.1.2/bin/beam.smp)
Failed to create scheduler thread 84, error = 11
Aborted (core dumped)
```

then I put:

```elixir
burrito/example (digit/beam-machine-download)$ grep custom mix.exs 
            linux_gnu: [os: :linux, cpu: :x86_64, libc: :gnu, custom_erts: "otp-25.2.3-linux-x86_64.tar.gz"],
```

The example gives a different error:

```elixir
$ ./example_cli_app_linux_gnu 
/home/kpanic/.local/share/.burrito/example_cli_app_erts-13.1.2_0.1.0/erts-13.1.2/bin/beam.smp: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

This is the full output of `BURRITO_TARGET=linux_gnu MIX_ENV=prod mix release`

```elixir
Release example_cli_app-0.1.0 already exists. Overwrite? [Yn] 
* assembling example_cli_app-0.1.0 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
> Target is being overridden with BURRITO_TARGET linux_gnu
> Burrito is building target: linux_gnu
> Burrito will build for target:
	OS: linux
	CPU: x86_64
	Qualifiers: [libc: :gnu]
	Debug: false
----> PHASE: :fetch
Custom build step!
Current Target: %Burrito.Builder.Target{alias: :linux_gnu, cpu: :x86_64, cross_build: false, debug?: false, erts_source: {:local, [path: "otp-25.2.3-linux-x86_64.tar.gz"]}, os: :linux, qualifiers: [libc: :gnu]}
--> Working directory: /tmp/burrito_build_09EB2C499DD76EF2
--> Resolving ERTS: {:local, [path: "otp-25.2.3-linux-x86_64.tar.gz"]}
--> Unpacked ERTS to: /tmp/unpacked_erts_AD16941F8B78E351
----> PHASE: :patch
--> Replacing ERTS binaries...
--> Overwriting NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so with /tmp/unpacked_erts_AD16941F8B78E351/otp-25.2.3-linux-x86_64/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/asn1-5.0.21/priv/lib/asn1rt_nif.so
--> Overwriting NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/crypto-5.1.2/priv/lib/crypto.so with /tmp/unpacked_erts_AD16941F8B78E351/otp-25.2.3-linux-x86_64/lib/crypto-5.1.2/priv/lib/crypto.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/crypto-5.1.2/priv/lib/crypto.so
--> Overwriting NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/crypto-5.1.2/priv/lib/otp_test_engine.so with /tmp/unpacked_erts_AD16941F8B78E351/otp-25.2.3-linux-x86_64/lib/crypto-5.1.2/priv/lib/otp_test_engine.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/crypto-5.1.2/priv/lib/otp_test_engine.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/megaco-4.4.2/priv/lib/megaco_flex_scanner_drv.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/megaco-4.4.2/priv/lib/megaco_flex_scanner_drv_mt.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/runtime_tools-1.19/priv/lib/dyntrace.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/runtime_tools-1.19/priv/lib/trace_file_drv.so
--> Installed NIF library /tmp/burrito_build_09EB2C499DD76EF2/lib/runtime_tools-1.19/priv/lib/trace_ip_drv.so
----> PHASE: :build
--> Generating wrapper metadata file...
info: Zig is building an Elixir binary... ⚡
info: Generating and compressing release payload... 📦
info: 🔍 Files Packed: 878
info: Archived 878 files into payload! 📥
info: Building wrapper and embedding payload... 🌯
info: Plugin found! /home/kpanic/src/burrito/example/./test_plugin/plugin.zig 🔌
info: DONE 🚀
--> Cleaning up...



🌯 Burrito has wrapped your Elixir app! 🌯
	Output Path: /home/kpanic/src/burrito/example/burrito_out/example_cli_app_linux_gnu


Custom build step!
Current Target: %Burrito.Builder.Target{alias: :linux_gnu, cpu: :x86_64, cross_build: false, debug?: false, erts_source: {:local_unpacked, [path: "/tmp/unpacked_erts_AD16941F8B78E351"]}, os: :linux, qualifiers: [libc: :gnu]}

Release created at _build/prod/rel/example_cli_app!

    # To start your system
    _build/prod/rel/example_cli_app/bin/example_cli_app start

Once the release is running:

    # To connect to it remotely
    _build/prod/rel/example_cli_app/bin/example_cli_app remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/prod/rel/example_cli_app/bin/example_cli_app stop

To list all commands:

    _build/prod/rel/example_cli_app/bin/example_cli_app
```

*NOTE*: I removed (`m -rf /home/kpanic/.local/share/.burrito`)  on the `host` and `target` machine but no sugar yet.

```elixir
$ ./example_cli_app_linux_gnu 
/home/kpanic/.local/share/.burrito/example_cli_app_erts-13.1.2_0.1.0/erts-13.1.2/bin/beam.smp: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

**Comment by doawoo** [comment] 2023-03-15 16:45
I'm having a hard time reproducing this on my end... I was able to run both a beam-machine release built on a fresh Manjaro install on a fresh Fedora 37 Workstation install (using the example app) 

The libtinfo5 error suggests that maybe you should install the `ncurses-compat-libs` package on the fedora machine.

**Comment by kpanic** [comment] 2023-03-15 16:52
Good that works for you @doawoo 
It's not a critical issue though.
The fedora machine that I am testing on is not mine (I don't have root access) so I can't install that package.

**Comment by kpanic** [comment] 2023-03-16 08:03
@doawoo out of curiosity, do you think that `libtinfo.so.5` can be statically linked too?

**Comment by doawoo** [comment] 2023-03-17 18:53
That's a pretty integral part of Erlang, and isn't something we can easily change on the Burrito side. It will take some research to see what can be done about trying to reduce the dependency on that library.

**Comment by doawoo** [comment] 2023-10-04 17:26
Closing this for now to clean up some issues -- the newer Erlang VMs I've built for the BEAM machine are going to be compiled with `--without-termcap` and have most deps statically compiled in, including the standard C library, and OpenSSL.

**Closed by doawoo** 2023-10-04 17:26 UTC
Labels: bug
