### ISSUE TITLE
Executable failed to run on win64: The system cannot find the path specified.

### ISSUE THREAD

**Issue by xhh** [burrito-elixir/burrito#9] opened 2021-11-08 12:12 UTC
I built executables for win64 and linux  on Ubuntu, the native (linux) one can run successfully on Ubuntu, but the .exe file can not run on my Windows PC (win version: 21H1), showing the following errors in PowerShell window:

```shell
PS D:\tmp> .\hello_burrito_cli_win64.exe
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
```

I found a similar issue [in the bakeware repo](https://github.com/bake-bake-bake/bakeware/issues/110), not sure if they are related.

**Comment by ashea-code** [comment] 2021-11-10 18:51
Interesting, I wonder if this is due to the lack of an AppData directory? Is there anything special about the installation of Winodws? Is the user anything special? We've had internal reports of IIS users causing issues.

**Comment by QuinnWilton** [comment] 2021-11-12 00:38
Hi @xhh! We ran into a similar issue in one of our deployments, because the application was being run as a user without an AppData directory (it was being run by Network Service as part of an IIS Worker). We added support for overriding the installation directory to get around this, and it may help you out here too.

Do you mind trying the latest version of Burrito? I would expect it to fail in your case, and give you instructions on how to override the directory, which you'll be able to do by setting the `APPLICATION_INSTALL_DIR` environment variable to another path.

More details here: https://github.com/burrito-elixir/burrito/pull/11

**Comment by xhh** [comment] 2021-11-12 08:15
Thanks for your quick response!
I've just updated to the latest commit of burrito and rebuilt a simple app, but still got the same errors (with no instructions).
I got this in *mix.lock", i.e. should be at the lastest commit.

```
"burrito": {:git, "https://github.com/burrito-elixir/burrito.git", "a5236e61dd9b915399d0c11ca3fd17d70dadf5d7", []}
```

**Comment by ashea-code** [comment] 2021-11-12 22:49
Would it be possible to give us some sort of minimal sample of the app? Also, does the example app in the repo itself build and launch for you?

Thanks!

**Comment by xhh** [comment] 2021-11-15 06:49
I'll try the example app and report the results (my network is having issue with downloading OTP from github right now).

**Comment by xhh** [comment] 2021-11-15 07:04
Just tried the example app, here's the output:

```shell
PS D:\tmp> .\example_cli_app_win64.exe
debug: Size of embedded payload is: 11481179
debug: Install Directory: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0
debug: Metadata path: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\_metadata.json
debug: Passing args string:
info: Test Plugin Init!
info: Test Plugin: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0
info: Test Plugin: {"app_name":"example_cli_app","app_version":"0.1.0","erts_version":"12.1.1","options":"[overwrite: false, quiet: false, strip_beams: true, burrito: [targets: [:win64, :linux], debug: true, plugin: \"./test_plugin/plugin.zig\", no_clean: false]]","zig_build_arguments":["-Dtarget=x86_64-windows-gnu"],"zig_version":"0.9.0-dev.1627+09c17acf0"}debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/COOKIE
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/consolidated/Elixir.IEx.Info.beam
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/consolidated/Elixir.Enumerable.beam
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/consolidated/Elixir.Collectable.beam
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/consolidated/Elixir.Jason.Encoder.beam
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/consolidated/Elixir.String.Chars.beam
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/consolidated/Elixir.List.Chars.beam
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/consolidated/Elixir.Inspect.beam
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/iex.bat
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/elixir.bat
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/example_cli_app.rel
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/start_clean.script
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/env.bat
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\releases/0.1.0/remote.vm.args
......
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\erts-12.1.1/bin/heart.exe
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\erts-12.1.1/bin/inet_gethost.exe
debug: Unpacked File: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\erts-12.1.1/bin/typer.exe
debug: Unpacked 805 files
debug: Going to clean up older versions of this application...
debug: Base Executable Path: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\bin\example_cli_app
debug: CLI List: { C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\bin\example_cli_app.bat, start, example_cli_app_win64.exe }
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
```

**Comment by xhh** [comment] 2021-11-15 07:21
It seems to be issue with the path. It is OK if I cd into the extracted path before running the exe file:

```shell
PS D:\tmp> cd C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0
PS C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0> D:\tmp\example_cli_app_win64.exe
......
debug: Unpacked 805 files
debug: Going to clean up older versions of this application...
debug: Base Executable Path: C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\bin\example_cli_app
debug: CLI List: { C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\bin\example_cli_app.bat, start, example_cli_app_win64.exe }
My arguments are: ["--no-halt", "--", "start", "example_cli_app_win64.exe"]
'Random' number is 600 ... luck of the draw!!
```

If I run the exe file in e.g. `D:\tmp`, the `RELEASE_ROOT` var in `bin\example_cli_app.bat` will be `D:\tmp`:

```bat
@echo off
setlocal enabledelayedexpansion

pushd .
cd "%~dp0\.."
set RELEASE_ROOT=%cd%
popd

echo RELEASE_ROOT: %RELEASE_ROOT%
```

```shell
PS D:\tmp> cd D:\tmp\
PS D:\tmp> C:\Users\xhh\AppData\Local\.tinfoil\example_cli_app_erts-12.1.1_0.1.0\bin\example_cli_app.bat
RELEASE_ROOT: D:\tmp
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Usage: example_cli_app.bat COMMAND [ARGS]
```

**Comment by ashea-code** [comment] 2021-11-15 21:07
OK good news I've been able to reproduce this locally on a Windows VM -- You're correct, there's something odd going on inside the path, it only happens when it's run from inside another volume (other than `C:`)
I'll investigate further!

**Comment by ashea-code** [comment] 2021-12-02 17:53
Hey there! we recently merged a new update to Burrito that changes the way the erlang VM is launched, could you give that a try and see if it resolves your issue?

Thanks!

**Comment by xhh** [comment] 2021-12-03 08:08
Just tried the example app again with the latest commit, and it works. Great job!

**Closed** 2021-12-03 08:08 UTC
